force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <description>Object represents a movie</description>
    <label>Movie</label>
    <nameField>
        <displayFormat>MOV-{0000}</displayFormat>
        <label>Movie Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Movie description</description>
    <label>Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <label>Genre</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Genres</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>movie title,</description>
    <inlineHelpText>255 char max</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/TMDBId__c.field-meta.xml
<CustomField>
    <fullName>TMDBId__c</fullName>
    <label>TMDB Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/TMDBSyncDate__c.field-meta.xml
<CustomField>
    <fullName>TMDBSyncDate__c</fullName>
    <label>TMDB Sync Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Review__c/Review__c.object-meta.xml
<CustomObject>
    <label>Review</label>
    <nameField>
        <label>Review Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Review__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <label>Comment</label>
    <length>70128</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Review__c/fields/Movie__c.field-meta.xml
<CustomField>
    <fullName>Movie__c</fullName>
    <label>Movie</label>
    <referenceTo>Movie__c</referenceTo>
    <relationshipLabel>Reviews</relationshipLabel>
    <relationshipName>Reviews</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TMBDIntegrationController.cls
public with sharing class TMBDIntegrationController {
    public class MovieResponseFromClient {
        @AuraEnabled
        public List<Integer> genre_ids { get; set; }
        @AuraEnabled
        public String overview { get; set; }
        @AuraEnabled
        public Decimal rating { get; set; }
        @AuraEnabled
        public String record_id { get; set; }
        @AuraEnabled
        public String title { get; set; }
    }

    @AuraEnabled(cacheable=true)
    public static List<Map<String, Object>> searchMovie(String title) {
        List<Map<String, Object>> results = new List<Map<String, Object>>();
        
        tmdb requestHandler = new tmdb();
        tmdbSearchMovieResponse response = requestHandler.searchMovie(title);
        List<tmdbSearchMovieResult> movies = response.results;

        for (tmdbSearchMovieResult movie : movies) {
            Map<String, Object> result = new Map<String, Object>();
            result.put('title', movie.original_title);
            result.put('rating', movie.vote_average);
            result.put('overview', movie.overview);
            result.put('record_id', movie.id);
            result.put('genre_ids', movie.genre_ids);

            results.add(result);
        }
        
        return results;
    }

    @AuraEnabled(cacheable=true)
    public static String getTitleOfExistingRecord(Id recordId) {
        Movie__c movie = [SELECT Title__c FROM Movie__c WHERE Id = :recordId LIMIT 1];
        return movie.Title__c;
    }

    private static Map<Integer, String> getOfficialGenres() {
        Map<Integer, String> result = new Map<Integer, String>();

        tmdb requestHandler = new tmdb();
        tmdbGenreListResponse response = requestHandler.genreList();

        for (tmdbGenre genre : response.genres) {
            result.put(genre.id, genre.name);
        }

        return result;
    }

    private static String processMovieGenre(Map<Integer, String> genres, MovieResponseFromClient movieNewData) {
        try {
            // Convert genre IDs to genre names
            List<String> genreNames = new List<String>();
            if (movieNewData.genre_ids != null) {
                for (Integer genreId : movieNewData.genre_ids) {
                    if (genres.containsKey(genreId)) {
                        String genreName = genres.get(genreId);
                        if (genreName.split(' ').size() > 1) {
                            genreName = genreName.replace(' ', '_');
                        }
                        genreNames.add(genreName);
                    }
                }
            }
            // Convert the List<String> genreNames to a single String for the multi-picklist
            if (genreNames != null && !genreNames.isEmpty()) {
                return String.join(genreNames, ';');
            } 
            return '';
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void updateMovieRecord(MovieResponseFromClient movieNewData, Id recordId) {
        Movie__c movie = [SELECT Id, TMDBId__c, TMDBSyncDate__c FROM Movie__c WHERE Id = :recordId LIMIT 1];

        movie.TMDBId__c = movieNewData.record_id;
        movie.TMDBSyncDate__c = Date.today();
        movie.Description__c = movieNewData.overview;
        movie.Rating__c = movieNewData.rating;

        Map<Integer, String> genres = getOfficialGenres();
        String processedGenres = processMovieGenre(genres, movieNewData);
        movie.Genre__c = processedGenres;
        
        update movie;
    }

    @AuraEnabled
    public static List<Review__c> getReviewsByMovieId(Id movieId) {
        List<Review__c> reviews = [
            SELECT Id, Author__c, Comment__c, Rating__c, CreatedDate, Avatar__c
            FROM Review__c 
            WHERE Movie__c = :movieId
            ORDER BY CreatedDate DESC
        ];

        return reviews;
    }
}