force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <description>Object represents a movie</description>
    <label>Movie</label>
    <nameField>
        <displayFormat>MOV-{0000}</displayFormat>
        <label>Movie Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie__c/fields/TMDBId__c.field-meta.xml
<CustomField>
    <fullName>TMDBId__c</fullName>
    <label>TMDB Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MovieTriggerHandler.cls
public with sharing class MovieTriggerHandler extends TriggerHandler {
    public override void afterInsert() {
        Set<Id> movieIds = new Set<Id>();

        for (Movie__c movie : (List<Movie__c>) Trigger.new) {
            if (movie.TMDBid__c != null) {
                movieIds.add(movie.Id);
            }
        }

        if (!movieIds.isEmpty()) {
            MovieServiceProvider.processMovies(movieIds);
        }
    }

    public override void afterUpdate() {
        Set<Id> movieIds = new Set<Id>();

        for (Integer i = 0; i < Trigger.new.size(); i++) {
            Movie__c newMovie = (Movie__c) Trigger.new[i];
            Movie__c oldMovie = (Movie__c) Trigger.old[i];
            
            if ((newMovie.TMDBid__c != null) && (newMovie.TMDBid__c != oldMovie.TMDBid__c)) {
                movieIds.add(newMovie.Id);
            }
        }

        if (!movieIds.isEmpty()) {
            MovieServiceProvider.processMovies(movieIds);
        }
    }
}