force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <description>Object represents a movie</description>
    <label>Movie</label>
    <nameField>
        <displayFormat>MOV-{0000}</displayFormat>
        <label>Movie Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie__c/fields/TMDBId__c.field-meta.xml
<CustomField>
    <fullName>TMDBId__c</fullName>
    <label>TMDB Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Movie/MovieTriggerHandler.cls
public with sharing class MovieTriggerHandler extends TriggerHandler {
    public override void afterInsert() {
        List<Movie__c> movies = (List<Movie__c>)Trigger.new;

        for (Movie__c movie : movies) {
            if (movie.TMDBid__c != null) {
                try {
                    MovieServiceProvider.updateMovieRecord(movie.TMDBid__c, movie.Id);
                } catch (Exception e) {
                    System.debug('Error queuing future method for TMDB_id ' + movie.TMDBid__c + ': ' + e.getMessage());
                }
            }
        }
    }

    public override void afterUpdate() {
        for (Integer i = 0; i < Trigger.new.size(); i++) {
            Movie__c newMovie = (Movie__c)Trigger.new[i];
            Movie__c oldMovie = (Movie__c)Trigger.old[i];
            
            if ((newMovie.TMDBid__c != null) && (newMovie.TMDBid__c != oldMovie.TMDBid__c)) {
                MovieServiceProvider.updateMovieRecord(newMovie.TMDBid__c, newMovie.Id);
            }
        }
    }
    
}