force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <description>Object represents a movie</description>
    <label>Movie</label>
    <nameField>
        <displayFormat>MOV-{0000}</displayFormat>
        <label>Movie Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <description>revenue generated</description>
    <label>Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/TMDBId__c.field-meta.xml
<CustomField>
    <fullName>TMDBId__c</fullName>
    <label>TMDB Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/TMDBSyncDate__c.field-meta.xml
<CustomField>
    <fullName>TMDBSyncDate__c</fullName>
    <label>TMDB Sync Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/TMDB/TMDBSyncBatch.cls
global class TMDBSyncBatch implements Database.Batchable<SObject>, Database.Stateful, Database.AllowsCallouts{
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator([
            SELECT Id, tmdbId__c, Revenue__c, Rating__c, TMDBSyncDate__c
            FROM Movie__c
            WHERE (TMDBSyncDate__c = NULL OR TMDBSyncDate__c <= LAST_N_DAYS:30)
            AND tmdbId__c != NULL
        ]);
    }
    
    global void execute(Database.BatchableContext BC, List<Movie__c> scope) {
        tmdb tmdbClient = new tmdb();
        List<Movie__c> moviesToUpdate = new List<Movie__c>();
        
        for (Movie__c movie : scope) {
            tmdMovieDetailResponse response = tmdbClient.movieDetailResponse(movie.TMDBid__c);
            movie.Revenue__c = response.revenue;
            movie.Rating__c = response.vote_average;
            movie.TMDBSyncDate__c = Date.today();

            moviesToUpdate.add(movie);
        }
        
        if (!moviesToUpdate.isEmpty()) {
            update moviesToUpdate;
        }
    }

    global void finish(Database.BatchableContext BC) {
        System.debug('Batch job finished');
    }

}