force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <description>Object represents a movie</description>
    <label>Movie</label>
    <nameField>
        <displayFormat>MOV-{0000}</displayFormat>
        <label>Movie Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <label>Budget</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Movie description</description>
    <label>Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <label>Genre</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Genres</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Movie__c/fields/LegacyId__c.field-meta.xml
<CustomField>
    <fullName>LegacyId__c</fullName>
    <label>Legacy Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Poster__c.field-meta.xml
<CustomField>
    <fullName>Poster__c</fullName>
    <description>Movie poster URL</description>
    <label>Poster</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/ReleaseDate__c.field-meta.xml
<CustomField>
    <fullName>ReleaseDate__c</fullName>
    <label>Release Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <description>revenue generated</description>
    <label>Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Script__c.field-meta.xml
<CustomField>
    <fullName>Script__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Script used in production</description>
    <label>Script</label>
    <referenceTo>Script__c</referenceTo>
    <relationshipLabel>Movies</relationshipLabel>
    <relationshipName>Movies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>movie title,</description>
    <inlineHelpText>255 char max</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/TMDBId__c.field-meta.xml
<CustomField>
    <fullName>TMDBId__c</fullName>
    <label>TMDB Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/TMDBSyncDate__c.field-meta.xml
<CustomField>
    <fullName>TMDBSyncDate__c</fullName>
    <label>TMDB Sync Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Script__c/Script__c.object-meta.xml
<CustomObject>
    <description>Script is a base for movie.</description>
    <label>Script</label>
    <nameField>
        <displayFormat>SCRT-{0000}</displayFormat>
        <label>Script Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Script__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Text description of the script</description>
    <inlineHelpText>Text 1000 symbols long</inlineHelpText>
    <label>Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Script__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <description>genre picklist</description>
    <label>Genre</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Genres</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Script__c/fields/LegacyId__c.field-meta.xml
<CustomField>
    <fullName>LegacyId__c</fullName>
    <label>Legacy Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Script__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>title of the script</description>
    <inlineHelpText>varchar(255)</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Movie/MovieServiceProvider.cls
public with sharing class MovieServiceProvider {
    @future(callout=true)
    public static void updateMovieRecords(Set<Id> movieIds) {
        List<Movie__c> moviesToUpdate = new List<Movie__c>();
        
        for (String movieId : movieIds) {
            Movie__c movie = [SELECT Id, TMDBid__c, Description__c, Title__c, Revenue__c, 
                  Rating__c, Poster__c, Budget__c
                  FROM Movie__c WHERE Id = :movieId LIMIT 1];

            tmdb tmdbClient = new tmdb();
            tmdMovieDetailResponse result = tmdbClient.movieDetailResponse(movie.TMDBid__c);

            movie.Description__c = result.overview;
            movie.Title__c = result.original_title;
            movie.Revenue__c = result.revenue;
            movie.Rating__c = result.vote_average;
            movie.Poster__c = result.poster_path;
            movie.Budget__c = result.budget;
            movie.TMDBSyncDate__c = Date.today();

            moviesToUpdate.add(movie);
        }

        update moviesToUpdate;
    }

    public void importJSON(String jsonString) {
        // Lists to store records to be inserted
        List<Movie__c> moviesToInsert = new List<Movie__c>();

        List<Script__c> scriptsToInsert = new List<Script__c>();
        List<Script__c> scriptsToUpdate = new List<Script__c>();

        // Maps to check existing records
        Map<String, Movie__c> existingMoviesMap = new Map<String, Movie__c>();
        Map<String, Script__c> existingScriptsMap = new Map<String, Script__c>();


        Map<String, String> scriptIdMap = new Map<String, String>();
        Map<String, String> movieScriptIdMap = new Map<String, String>();


        // Query existing movies and scripts
        for (Movie__c movie : [SELECT tmdbId__c, LegacyId__c FROM Movie__c]) {
            existingMoviesMap.put(movie.tmdbId__c, movie);
        }
        for (Script__c script : [SELECT LegacyId__c, Id FROM Script__c]) {
            existingScriptsMap.put(script.LegacyId__c, script);
        }

        List<MovieData.Movie> movieList = (List<MovieData.Movie>) JSON.deserialize(jsonString, List<MovieData.Movie>.class);

        for (MovieData.Movie movieData : movieList) {
            // Check if the movie already exists by tmdb_id
            if (!existingMoviesMap.containsKey(movieData.tmdb_id)) {
                Movie__c newMovie = new Movie__c();
                newMovie.LegacyId__c = movieData.id;
                newMovie.Title__c = movieData.name;
                newMovie.tmdbId__c = movieData.tmdb_id;
                newMovie.genre__c = movieData.genre;
                newMovie.rating__c = movieData.rating;
                newMovie.budget__c = movieData.budget;
                newMovie.Revenue__c = movieData.revenue;
                newMovie.Description__c = movieData.script != null ? movieData.script.description : null;

                // date conversion with try-catch
                if (movieData.release_date != null) {
                    try {
                        // Parse  string and convert date format from dd/MM/yyyy to yyyy-MM-dd
                        String release = movieData.release_date.replaceAll('(\\d{1,2})\\/(\\d{1,2})\\/(\\d{4})', '$3-$2-$1');
                        newMovie.ReleaseDate__c = Date.valueOf(release);
                    } catch (Exception e) {
                        System.debug('Invalid date format for movie: ' + movieData.name);
                    }
                }

                // Handle script data
                if (movieData.script != null) {
                    Script__c script;
                    if (existingScriptsMap.containsKey(movieData.script.id)) {
                        // Use existing script
                        script = existingScriptsMap.get(movieData.script.id);
                        scriptsToUpdate.add(script);
                    } else {
                        // Create new script record
                        script = new Script__c();
                        script.LegacyId__c = movieData.script.id;
                        script.Title__c = movieData.script.name;
                        script.Description__c = movieData.script.description;
                        scriptsToInsert.add(script);
                    }
                
                    scriptIdMap.put(movieData.id, movieData.script.id);
                }
                moviesToInsert.add(newMovie);
            }
        }

        // Insert scripts first to get their Ids
        if (!scriptsToInsert.isEmpty()) {
            insert scriptsToInsert;
        }

        scriptsToInsert.addAll(scriptsToUpdate);
        for (Script__c script : scriptsToInsert) {
            movieScriptIdMap.put(script.LegacyId__c, script.Id);
        }

        // Assign the correct Script__c Ids to movies before inserting them
        for (Movie__c movie : moviesToInsert) {
            if (scriptIdMap.containsKey(movie.LegacyId__c)) {
                movie.Script__c = movieScriptIdMap.get(scriptIdMap.get(movie.LegacyId__c));
            }
        }

        // Insert movies
        if (!moviesToInsert.isEmpty()) {
            insert moviesToInsert;
        }
    }
}